# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/lion/workspace/code/instaseis/instaseis/gui/qt_window.ui'
#
# Created: Wed Oct 22 12:05:03 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(1350, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1350, 900))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.z_graph = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z_graph.sizePolicy().hasHeightForWidth())
        self.z_graph.setSizePolicy(sizePolicy)
        self.z_graph.setObjectName(_fromUtf8("z_graph"))
        self.verticalLayout_2.addWidget(self.z_graph)
        self.n_graph = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_graph.sizePolicy().hasHeightForWidth())
        self.n_graph.setSizePolicy(sizePolicy)
        self.n_graph.setObjectName(_fromUtf8("n_graph"))
        self.verticalLayout_2.addWidget(self.n_graph)
        self.e_graph = PlotWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_graph.sizePolicy().hasHeightForWidth())
        self.e_graph.setSizePolicy(sizePolicy)
        self.e_graph.setObjectName(_fromUtf8("e_graph"))
        self.verticalLayout_2.addWidget(self.e_graph)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.select_folder_button = QtGui.QPushButton(self.centralwidget)
        self.select_folder_button.setMaximumSize(QtCore.QSize(150, 50))
        self.select_folder_button.setObjectName(_fromUtf8("select_folder_button"))
        self.horizontalLayout_2.addWidget(self.select_folder_button)
        self.db_path_label = QtGui.QLabel(self.centralwidget)
        self.db_path_label.setText(_fromUtf8(""))
        self.db_path_label.setObjectName(_fromUtf8("db_path_label"))
        self.horizontalLayout_2.addWidget(self.db_path_label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.info_label = QtGui.QLabel(self.centralwidget)
        self.info_label.setText(_fromUtf8(""))
        self.info_label.setObjectName(_fromUtf8("info_label"))
        self.verticalLayout.addWidget(self.info_label)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.source_latitude = QtGui.QDoubleSpinBox(self.groupBox)
        self.source_latitude.setMinimum(-90.0)
        self.source_latitude.setMaximum(90.0)
        self.source_latitude.setObjectName(_fromUtf8("source_latitude"))
        self.gridLayout_2.addWidget(self.source_latitude, 1, 0, 1, 1)
        self.source_longitude = QtGui.QDoubleSpinBox(self.groupBox)
        self.source_longitude.setMinimum(-180.0)
        self.source_longitude.setMaximum(180.0)
        self.source_longitude.setObjectName(_fromUtf8("source_longitude"))
        self.gridLayout_2.addWidget(self.source_longitude, 1, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.depth_label = QtGui.QLabel(self.groupBox)
        self.depth_label.setMinimumSize(QtCore.QSize(120, 0))
        self.depth_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.depth_label.setObjectName(_fromUtf8("depth_label"))
        self.horizontalLayout_3.addWidget(self.depth_label)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.depth_slider = QtGui.QSlider(self.groupBox)
        self.depth_slider.setMinimum(-300)
        self.depth_slider.setMaximum(0)
        self.depth_slider.setProperty("value", -10)
        self.depth_slider.setSliderPosition(-10)
        self.depth_slider.setOrientation(QtCore.Qt.Vertical)
        self.depth_slider.setTickPosition(QtGui.QSlider.NoTicks)
        self.depth_slider.setObjectName(_fromUtf8("depth_slider"))
        self.gridLayout_4.addWidget(self.depth_slider, 0, 1, 2, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.mt_fig = Qt4MplCanvas(self.groupBox)
        self.mt_fig.setMinimumSize(QtCore.QSize(60, 60))
        self.mt_fig.setMaximumSize(QtCore.QSize(60, 60))
        self.mt_fig.setObjectName(_fromUtf8("mt_fig"))
        self.horizontalLayout.addWidget(self.mt_fig)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.m_rr = QtGui.QDoubleSpinBox(self.groupBox)
        self.m_rr.setPrefix(_fromUtf8(""))
        self.m_rr.setMinimum(-99.0)
        self.m_rr.setMaximum(99.0)
        self.m_rr.setObjectName(_fromUtf8("m_rr"))
        self.gridLayout.addWidget(self.m_rr, 1, 1, 1, 1)
        self.m_rt = QtGui.QDoubleSpinBox(self.groupBox)
        self.m_rt.setPrefix(_fromUtf8(""))
        self.m_rt.setMinimum(-99.0)
        self.m_rt.setMaximum(99.0)
        self.m_rt.setObjectName(_fromUtf8("m_rt"))
        self.gridLayout.addWidget(self.m_rt, 1, 2, 1, 2)
        self.m_rp = QtGui.QDoubleSpinBox(self.groupBox)
        self.m_rp.setPrefix(_fromUtf8(""))
        self.m_rp.setMinimum(-99.0)
        self.m_rp.setMaximum(99.0)
        self.m_rp.setObjectName(_fromUtf8("m_rp"))
        self.gridLayout.addWidget(self.m_rp, 1, 4, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.m_tt = QtGui.QDoubleSpinBox(self.groupBox)
        self.m_tt.setPrefix(_fromUtf8(""))
        self.m_tt.setMinimum(-99.0)
        self.m_tt.setMaximum(99.0)
        self.m_tt.setObjectName(_fromUtf8("m_tt"))
        self.gridLayout.addWidget(self.m_tt, 2, 2, 1, 2)
        self.m_tp = QtGui.QDoubleSpinBox(self.groupBox)
        self.m_tp.setPrefix(_fromUtf8(""))
        self.m_tp.setMinimum(-99.0)
        self.m_tp.setMaximum(99.0)
        self.m_tp.setObjectName(_fromUtf8("m_tp"))
        self.gridLayout.addWidget(self.m_tp, 2, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 2)
        self.m_pp = QtGui.QDoubleSpinBox(self.groupBox)
        self.m_pp.setPrefix(_fromUtf8(""))
        self.m_pp.setMinimum(-99.0)
        self.m_pp.setMaximum(99.0)
        self.m_pp.setObjectName(_fromUtf8("m_pp"))
        self.gridLayout.addWidget(self.m_pp, 3, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.map_fig = Qt4MplCanvas(self.centralwidget)
        self.map_fig.setMinimumSize(QtCore.QSize(470, 280))
        self.map_fig.setMaximumSize(QtCore.QSize(470, 280))
        self.map_fig.setObjectName(_fromUtf8("map_fig"))
        self.verticalLayout.addWidget(self.map_fig)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.receiver_latitude = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.receiver_latitude.setMinimum(-90.0)
        self.receiver_latitude.setMaximum(90.0)
        self.receiver_latitude.setProperty("value", 45.0)
        self.receiver_latitude.setObjectName(_fromUtf8("receiver_latitude"))
        self.gridLayout_3.addWidget(self.receiver_latitude, 0, 1, 1, 1)
        self.receiver_longitude = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.receiver_longitude.setMinimum(-180.0)
        self.receiver_longitude.setMaximum(180.0)
        self.receiver_longitude.setProperty("value", 45.0)
        self.receiver_longitude.setObjectName(_fromUtf8("receiver_longitude"))
        self.gridLayout_3.addWidget(self.receiver_longitude, 1, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_4.setStretch(0, 10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Instaseis GUI", None))
        self.select_folder_button.setText(_translate("MainWindow", "Select Folder", None))
        self.groupBox.setTitle(_translate("MainWindow", "Source", None))
        self.label.setText(_translate("MainWindow", "Latitude", None))
        self.label_2.setText(_translate("MainWindow", "Longitude", None))
        self.depth_label.setText(_translate("MainWindow", "Depth: 10 km", None))
        self.label_5.setText(_translate("MainWindow", "r", None))
        self.label_9.setText(_translate("MainWindow", "p", None))
        self.label_4.setText(_translate("MainWindow", "r", None))
        self.m_rr.setSuffix(_translate("MainWindow", "e16", None))
        self.m_rt.setSuffix(_translate("MainWindow", "e16", None))
        self.m_rp.setSuffix(_translate("MainWindow", "e16", None))
        self.label_7.setText(_translate("MainWindow", "t", None))
        self.m_tt.setSuffix(_translate("MainWindow", "e16", None))
        self.m_tp.setSuffix(_translate("MainWindow", "e16", None))
        self.label_8.setText(_translate("MainWindow", "p", None))
        self.m_pp.setSuffix(_translate("MainWindow", "e16", None))
        self.label_6.setText(_translate("MainWindow", "t", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Receiver", None))
        self.label_11.setText(_translate("MainWindow", "Latitude", None))
        self.label_12.setText(_translate("MainWindow", "Longitude", None))

from instaseis.gui.qt4mplcanvas import Qt4MplCanvas
from pyqtgraph import PlotWidget
